default["elb"]["name"]="mage"
default['load']['response_time_seconds'] = 10
default['latency']['back_in_time_minutes'] = 5
default['load']['cron_check_every_x_minutes'] = 5
default['load']['cron_log_file'] = '/home/ubuntu/check_load.log'
default['load']['cron_err_file'] = '/home/ubuntu/check_load.err'
default['maintenance_page']['webserver_search_expr'] = "roles:magento-webonly"
default['elb']['javahome']="/usr/lib/jvm/java-6-openjdk-amd64"
default['maintenance']['manually_switched_on']="false"
default['maintenance']['automatically_switched_on']="false"
default['elb']['maintenance_page']['health_check_url']='health_check.html'
default['elb']['maintenance_page']['health_check_interval']='5'
default['elb']['maintenance_page']['health_check_timeout']='3'
default['elb']['maintenance_page']['health_check_unhealthy_treshhold']='2'
default['elb']['maintenance_page']['health_check_healthy_treshhold']='2'
default['elb']['site']['health_check_url']='index.html'
default['elb']['site']['health_check_interval']='5'
default['elb']['site']['health_check_timeout']='3'
default['elb']['site']['health_check_unhealthy_treshhold']='2'
default['elb']['site']['health_check_healthy_treshhold']='2'
default['pony']['mail']['to']='flopaconsult@gmail.com'
default['pony']['mail']['from']='cloudtrainingschef@gmail.com'
default['pony']['mail']['subject']['switch_on']='Maintenance page is on'
default['pony']['mail']['body']['switch_on']='Maintenance page is on'
default['pony']['mail']['smtp_server']='smtp.gmail.com'
default['pony']['mail']['smtp_port']='587'
default['pony']['mail']['smtp_username']='cloudtrainingschef'
default['pony']['mail']['smtp_password']='florin0704'
default['pony']['mail']['domain']='localhost.localdomain'
